export const PERSON_REQUEST = 'PERSON_REQUEST';
export const PERSON_SAVED_SUCCESS = 'PERSON_SAVED_SUCCESS';
export const PERSON_SUCCESS = 'PERSON_SUCCESS';
export const PERSON_FAILURE = 'PERSON_FAILURE';